Config = {}

-- Pulse and Threshold Settings
Config.PulseInterval = 300  -- Seconds between world pulse checks
Config.ProxThreshold = 1000 -- Meters for proximity (1km)
Config.MinUnitsP1 = 2      -- Minimum units for Priority 1 calls
Config.QueueLimit = 5      -- Max queued calls before overflow

-- Departments (For reference; dispatch uses zone primaries/secondaries)
Config.Departments = {
    POLICE = {"LSPD", "LSCSO", "LSPA", "LSIAPD", "BCSO", "SSPD", "PBPD", "SAGW", "SAST"},
    FIRE = {"LSFD", "LSIAFD", "BCFD", "PBFD"},
    EMS = {"LSEMS", "BCEMS", "PBEMS"}
}

-- Unified Code Registry (Full from sources: EMS numeric, Fire Fxx, Police 10-xx)
Config.Codes = {
    -- EMS Codes (Modified EMS_Rescue.xlsx with Fire Medical Crossovers)
    ["1"] = {priority = 2, desc = "Heat exhaustion", primaryAgency = "EMS", linked = {"F21"}, peds = "1-2"},
    ["2"] = {priority = 1, desc = "Heat stroke", primaryAgency = "EMS", linked = {"F21"}, peds = "1"},
    ["3"] = {priority = 1, desc = "Seizure", primaryAgency = "EMS", linked = {"80"}, peds = "1"},
    ["4"] = {priority = 2, desc = "Diabetic reaction", primaryAgency = "EMS", linked = {"46"}, peds = "1"},
    ["5"] = {priority = 1, desc = "Insulin shock", primaryAgency = "EMS", linked = {"44"}, peds = "1"},
    ["6"] = {priority = 1, desc = "Poisoning", primaryAgency = "EMS", linked = {"F21"}, peds = "1-3"},
    ["7"] = {priority = 2, desc = "Communicable disease", primaryAgency = "EMS", linked = {"42"}, peds = "1"},
    ["8"] = {priority = 1, desc = "Unconscious", primaryAgency = "EMS", linked = {"83"}, peds = "1"},
    ["9"] = {priority = 3, desc = "Dead on arrival - No Transport", primaryAgency = "EMS", linked = {"10-79"}, peds = "1"},
    ["9a"] = {priority = 2, desc = "Possible dead", primaryAgency = "EMS", linked = {"9"}, peds = "1"},
    ["10"] = {priority = 3, desc = "Dead on arrival - Transport", primaryAgency = "EMS", linked = {"9"}, peds = "1"},
    ["11"] = {priority = 2, desc = "Abrasion/contusion", primaryAgency = "EMS", linked = {"13"}, peds = "1-2"},
    ["12"] = {priority = 1, desc = "Convulsion", primaryAgency = "EMS", linked = {"F3a"}, peds = "1"},
    ["13"] = {priority = 2, desc = "Laceration", primaryAgency = "EMS", linked = {"17"}, peds = "1"},
    ["14"] = {priority = 1, desc = "Stab wound", primaryAgency = "EMS", linked = {"10-32"}, peds = "1"},
    ["15"] = {priority = 1, desc = "Gunshot wound", primaryAgency = "EMS", linked = {"10-32"}, peds = "1"},
    ["16"] = {priority = 1, desc = "Burn", primaryAgency = "EMS", linked = {"F2a", "F3b"}, peds = "1-3"},
    ["17"] = {priority = 1, desc = "Hemorrhage", primaryAgency = "EMS", linked = {"15"}, peds = "1"},
    ["18"] = {priority = 1, desc = "Electrocution", primaryAgency = "EMS", linked = {"F6"}, peds = "1"},
    ["19"] = {priority = 1, desc = "Chest injury", primaryAgency = "EMS", linked = {"80"}, peds = "1"},
    ["20"] = {priority = 1, desc = "Crushing", primaryAgency = "EMS", linked = {"F28a"}, peds = "1"},
    ["21"] = {priority = 1, desc = "Amputation", primaryAgency = "EMS", linked = {"20"}, peds = "1"},
    ["22"] = {priority = 2, desc = "Dislocation", primaryAgency = "EMS", linked = {"23"}, peds = "1"},
    ["23"] = {priority = 2, desc = "Fracture", primaryAgency = "EMS", linked = {"35"}, peds = "1-2"},
    ["24"] = {priority = 1, desc = "Multi trauma", primaryAgency = "EMS", linked = {"19", "23"}, peds = "1"},
    ["25"] = {priority = 1, desc = "Victim trapped", primaryAgency = "EMS", linked = {"F7"}, peds = "1"},
    ["26"] = {priority = 1, desc = "Motor vehicle accident", primaryAgency = "EMS", linked = {"F26", "10-50"}, peds = "2-4"},
    ["27"] = {priority = 1, desc = "Pedestrian hit by vehicle", primaryAgency = "EMS", linked = {"26"}, peds = "1"},
    ["28a"] = {priority = 1, desc = "Other accident-Bus", primaryAgency = "EMS", linked = {"F28a"}, peds = "5-10"},
    ["28b"] = {priority = 1, desc = "Other accident-Train", primaryAgency = "EMS", linked = {"F28b"}, peds = "3-6"},
    ["28c"] = {priority = 1, desc = "Other accident-Aircraft", primaryAgency = "EMS", linked = {"F28c"}, peds = "4-8"},
    ["30"] = {priority = 1, desc = "Head injury", primaryAgency = "EMS", linked = {"33"}, peds = "1"},
    ["31"] = {priority = 1, desc = "Paralysis", primaryAgency = "EMS", linked = {"32"}, peds = "1"},
    ["32"] = {priority = 1, desc = "Spinal injury", primaryAgency = "EMS", linked = {"31"}, peds = "1"},
    ["33"] = {priority = 1, desc = "CVA/TIA stroke", primaryAgency = "EMS", linked = {"80"}, peds = "1"},
    ["34"] = {priority = 2, desc = "Hypotension", primaryAgency = "EMS", linked = {"82"}, peds = "1"},
    ["35"] = {priority = 3, desc = "Sprain/strain", primaryAgency = "EMS", linked = {"23"}, peds = "1"},
    ["36"] = {priority = 3, desc = "Headache", primaryAgency = "EMS", linked = {"30"}, peds = "1"},
    ["37"] = {priority = 2, desc = "Animal bite", primaryAgency = "EMS", linked = {"10-11"}, peds = "1"},
    ["40"] = {priority = 2, desc = "Hysteria", primaryAgency = "EMS", linked = {"43"}, peds = "1"},
    ["41"] = {priority = 2, desc = "Syncope", primaryAgency = "EMS", linked = {"8"}, peds = "1"},
    ["42"] = {priority = 3, desc = "Cold, flu", primaryAgency = "EMS", linked = {"7"}, peds = "1"},
    ["43"] = {priority = 2, desc = "Psychiatric", primaryAgency = "EMS", linked = {"43a"}, peds = "1"},
    ["43a"] = {priority = 1, desc = "Suicide attempt", primaryAgency = "EMS", linked = {"44"}, peds = "1"},
    ["44"] = {priority = 1, desc = "Overdose", primaryAgency = "EMS", linked = {"5"}, peds = "1"},
    ["45"] = {priority = 1, desc = "CSAI", primaryAgency = "EMS", linked = {"14"}, peds = "1"},
    ["46"] = {priority = 2, desc = "General weakness", primaryAgency = "EMS", linked = {"34"}, peds = "1"},
    ["50"] = {priority = 2, desc = "Vomiting", primaryAgency = "EMS", linked = {"6"}, peds = "1"},
    ["51"] = {priority = 2, desc = "G.I. Problems", primaryAgency = "EMS", linked = {"50"}, peds = "1"},
    ["52"] = {priority = 2, desc = "G.U. Problems", primaryAgency = "EMS", linked = {"64"}, peds = "1"},
    ["53"] = {priority = 2, desc = "Cancer", primaryAgency = "EMS", linked = {"46"}, peds = "1"},
    ["54"] = {priority = 2, desc = "Dehydration", primaryAgency = "EMS", linked = {"1"}, peds = "1"},
    ["60"] = {priority = 2, desc = "OB Prenatal", primaryAgency = "EMS", linked = {"62"}, peds = "1"},
    ["61"] = {priority = 2, desc = "OB Postnatal", primaryAgency = "EMS", linked = {"60"}, peds = "1"},
    ["62"] = {priority = 1, desc = "OB Emergency", primaryAgency = "EMS", linked = {"63"}, peds = "1"},
    ["63"] = {priority = 1, desc = "OB Abortion", primaryAgency = "EMS", linked = {"62"}, peds = "1"},
    ["64"] = {priority = 2, desc = "GYN Problem", primaryAgency = "EMS", linked = {"52"}, peds = "1"},
    ["65"] = {priority = 1, desc = "Sexual assault", primaryAgency = "EMS", linked = {"45"}, peds = "1"},
    ["70"] = {priority = 1, desc = "Apnea", primaryAgency = "EMS", linked = {"71"}, peds = "1"},
    ["71"] = {priority = 1, desc = "Choking / airway obstruction", primaryAgency = "EMS", linked = {"70"}, peds = "1"},
    ["72"] = {priority = 2, desc = "Hyperventilation", primaryAgency = "EMS", linked = {"74"}, peds = "1"},
    ["73"] = {priority = 1, desc = "Pulmonary edema", primaryAgency = "EMS", linked = {"81"}, peds = "1"},
    ["74"] = {priority = 1, desc = "Respiratory distress", primaryAgency = "EMS", linked = {"73"}, peds = "1"},
    ["75"] = {priority = 1, desc = "Anaphylactic shock", primaryAgency = "EMS", linked = {"37"}, peds = "1"},
    ["76"] = {priority = 1, desc = "Near drowning", primaryAgency = "EMS", linked = {"F11"}, peds = "1"},
    ["77"] = {priority = 2, desc = "Hypothermia", primaryAgency = "EMS", linked = {"F4"}, peds = "1"},
    ["78"] = {priority = 1, desc = "Hazmat team call", primaryAgency = "EMS", linked = {"F21"}, peds = "1-2"},
    ["79"] = {priority = 2, desc = "Assist fire department", primaryAgency = "EMS", linked = {"F7"}, peds = "0"},
    ["80"] = {priority = 1, desc = "Cardiac problems", primaryAgency = "EMS", linked = {"83"}, peds = "1"},
    ["81"] = {priority = 1, desc = "Congestive heart failure", primaryAgency = "EMS", linked = {"80"}, peds = "1"},
    ["82"] = {priority = 2, desc = "Hypertension", primaryAgency = "EMS", linked = {"34"}, peds = "1"},
    ["83"] = {priority = 1, desc = "Cardiac arrest", primaryAgency = "EMS", linked = {"8"}, peds = "1"},
    ["84"] = {priority = 3, desc = "Discontinue resuscitation", primaryAgency = "EMS", linked = {"9"}, peds = "1"},
    ["88"] = {priority = 1, desc = "Mass casualty response", primaryAgency = "EMS", linked = {"F28", "F20"}, peds = "10-20"},
    ["90"] = {priority = 3, desc = "Unknown problem", primaryAgency = "EMS", linked = {}, peds = "1"},
    ["91"] = {priority = 3, desc = "Transport for exam", primaryAgency = "EMS", linked = {"Any"}, peds = "1"},
    ["92"] = {priority = 3, desc = "Non-emergency transport", primaryAgency = "EMS", linked = {"91"}, peds = "1"},
    ["93"] = {priority = 3, desc = "No transport", primaryAgency = "EMS", linked = {"90"}, peds = "1"},
    ["94"] = {priority = 3, desc = "Cancelled call", primaryAgency = "EMS", linked = {}, peds = "0"},
    ["95"] = {priority = 3, desc = "False call", primaryAgency = "EMS", linked = {"94"}, peds = "0"},
    ["96"] = {priority = 2, desc = "Special assignment", primaryAgency = "EMS", linked = {"99"}, peds = "0"},
    ["97"] = {priority = 1, desc = "High angle rescue team call", primaryAgency = "EMS", linked = {"F4"}, peds = "1"},
    ["98"] = {priority = 1, desc = "SWAT team call", primaryAgency = "EMS", linked = {"10-33"}, peds = "2-4"},
    ["99"] = {priority = 1, desc = "Neonatal transport", primaryAgency = "EMS", linked = {"60"}, peds = "1"},
    ["100"] = {priority = 1, desc = "Dive rescue team call - drowning", primaryAgency = "EMS", linked = {"F11"}, peds = "1"},

    -- Fire Codes (FireCodes.xlsx)
    ["F1a"] = {priority = 2, desc = "Grass Fire", primaryAgency = "FIRE", linked = {"EMS77"}, peds = "0-1"},
    ["F1b"] = {priority = 2, desc = "Trash/Dumpster fire", primaryAgency = "FIRE", linked = {}, peds = "0"},
    ["F2a"] = {priority = 1, desc = "One story dwelling", primaryAgency = "FIRE", linked = {"EMS16", "F7"}, peds = "1-3"},
    ["F2b"] = {priority = 1, desc = "One story business", primaryAgency = "FIRE", linked = {"F2a"}, peds = "2-4"},
    ["F2c"] = {priority = 1, desc = "Mobile home", primaryAgency = "FIRE", linked = {"F2a"}, peds = "1-2"},
    ["F2d"] = {priority = 2, desc = "Other structure", primaryAgency = "FIRE", linked = {"F2a"}, peds = "1"},
    ["F3a"] = {priority = 1, desc = "Multi story building", primaryAgency = "FIRE", linked = {"EMS12"}, peds = "3-5"},
    ["F3b"] = {priority = 1, desc = "Multi story business", primaryAgency = "FIRE", linked = {"F3a"}, peds = "4-6"},
    ["F4"] = {priority = 2, desc = "Woods/brush fire", primaryAgency = "FIRE", linked = {"EMS1"}, peds = "0-2"},
    ["F5"] = {priority = 1, desc = "Vehicle fire", primaryAgency = "FIRE", linked = {"EMS26"}, peds = "1-2"},
    ["F6"] = {priority = 1, desc = "Electrical fire", primaryAgency = "FIRE", linked = {"EMS18"}, peds = "1"},
    ["F7"] = {priority = 1, desc = "Victim trapped inside", primaryAgency = "FIRE", linked = {"EMS25"}, peds = "1-3"},
    ["F8"] = {priority = 3, desc = "First responder call", primaryAgency = "FIRE", linked = {}, peds = "0"},
    ["F10"] = {priority = 3, desc = "Reported death by fire", primaryAgency = "FIRE", linked = {"EMS9"}, peds = "1"},
    ["F11"] = {priority = 3, desc = "Reported death by drowning", primaryAgency = "FIRE", linked = {"EMS76"}, peds = "1"},
    ["F12"] = {priority = 3, desc = "Death by vehicle accident", primaryAgency = "FIRE", linked = {"EMS26"}, peds = "1"},
    ["F15"] = {priority = 2, desc = "Unit on special assignment", primaryAgency = "FIRE", linked = {"96"}, peds = "0"},
    ["F20"] = {priority = 1, desc = "Danger fire spreading", primaryAgency = "FIRE", linked = {"F3a"}, peds = "2-4"},
    ["F21"] = {priority = 1, desc = "Hazardous material/Hazmat", primaryAgency = "FIRE", linked = {"EMS6", "78"}, peds = "1-3"},
    ["F25"] = {priority = 3, desc = "Wash down street", primaryAgency = "FIRE", linked = {}, peds = "0"},
    ["F26"] = {priority = 1, desc = "Auto Accident", primaryAgency = "FIRE", linked = {"EMS26", "10-50"}, peds = "2-4"},
    ["F28"] = {priority = 1, desc = "Man made disaster", primaryAgency = "FIRE", linked = {"EMS88"}, peds = "5-10"},
    ["F28a"] = {priority = 1, desc = "Bus accident", primaryAgency = "FIRE", linked = {"F28", "EMS28a"}, peds = "5-10"},
    ["F28b"] = {priority = 1, desc = "Train accident", primaryAgency = "FIRE", linked = {"F28"}, peds = "3-6"},
    ["F28c"] = {priority = 1, desc = "Aircraft accident", primaryAgency = "FIRE", linked = {"F28"}, peds = "4-8"},

    -- Police 10-Codes (From tencodeg.pdf and image table)
    ["10-1"] = {priority = 2, desc = "Unable to Copy - Change Location", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-2"] = {priority = 3, desc = "Signal Good", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-3"] = {priority = 3, desc = "Stop Transmitting", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-4"] = {priority = 3, desc = "Acknowledgment (OK)", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-5"] = {priority = 3, desc = "Relay", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-6"] = {priority = 2, desc = "Busy-Unless Urgent", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-7"] = {priority = 3, desc = "Out of Service", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-8"] = {priority = 3, desc = "In Service", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-9"] = {priority = 3, desc = "Repeat", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-10"] = {priority = 1, desc = "Fight in Progress", primaryAgency = "POLICE", linked = {"EMS45"}, peds = "2-4"},
    ["10-11"] = {priority = 2, desc = "Dog Case", primaryAgency = "POLICE", linked = {"37"}, peds = "1"},
    ["10-12"] = {priority = 3, desc = "Stand By (Stop)", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-13"] = {priority = 2, desc = "Weather - Road Report", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-14"] = {priority = 2, desc = "Prowler Report", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-15"] = {priority = 1, desc = "Civil Disturbance", primaryAgency = "POLICE", linked = {"10-16"}, peds = "3-5"},
    ["10-16"] = {priority = 2, desc = "Domestic Problem", primaryAgency = "POLICE", linked = {"EMS43"}, peds = "2"},
    ["10-17"] = {priority = 3, desc = "Meet Complainant", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-18"] = {priority = 1, desc = "Quickly", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-19"] = {priority = 3, desc = "Return to ___", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-20"] = {priority = 3, desc = "Location", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-21"] = {priority = 3, desc = "Call (__) by Phone", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-22"] = {priority = 3, desc = "Disregard", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-23"] = {priority = 3, desc = "Arrived at Scene", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-24"] = {priority = 3, desc = "Assignment Completed", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-25"] = {priority = 3, desc = "Report in Person (Meet)", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-26"] = {priority = 2, desc = "Detaining Subject, Expedite", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-27"] = {priority = 3, desc = "(Driver) License Information", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-28"] = {priority = 3, desc = "Vehicle Registration Information", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-29"] = {priority = 2, desc = "Check for Wanted", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-30"] = {priority = 3, desc = "Unnecessary Use of Radio", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-31"] = {priority = 1, desc = "Crime in Progress", primaryAgency = "POLICE", linked = {"10-32"}, peds = "1-2"},
    ["10-32"] = {priority = 1, desc = "Man with Gun", primaryAgency = "POLICE", linked = {"EMS15"}, peds = "1"},
    ["10-33"] = {priority = 1, desc = "Emergency", primaryAgency = "POLICE", linked = {"All"}, peds = "0"},
    ["10-34"] = {priority = 1, desc = "Riot", primaryAgency = "POLICE", linked = {"10-15"}, peds = "5-10"},
    ["10-35"] = {priority = 1, desc = "Major Crime Alert", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-36"] = {priority = 3, desc = "Correct Time", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-37"] = {priority = 2, desc = "(Investigate) Suspicious Vehicle", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-38"] = {priority = 2, desc = "Stopping Suspicious Vehicle", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-39"] = {priority = 1, desc = "Urgent - Use Light, Siren", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-40"] = {priority = 2, desc = "Silent Run - No Light, Siren", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-41"] = {priority = 3, desc = "Beginning Tour of Duty", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-42"] = {priority = 3, desc = "Ending Tour of Duty", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-43"] = {priority = 3, desc = "Information", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-44"] = {priority = 3, desc = "Permission to Leave __ for __", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-45"] = {priority = 3, desc = "Animal Carcass at __", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-46"] = {priority = 2, desc = "Assist Motorist", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-47"] = {priority = 2, desc = "Emergency Road Repair at ___", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-48"] = {priority = 3, desc = "Traffic Standard Repair at ___", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-49"] = {priority = 2, desc = "Traffic Light Out at ___", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-50"] = {priority = 1, desc = "Accident (F, PI, PD)", primaryAgency = "POLICE", linked = {"EMS26", "F26"}, peds = "2-4"},
    ["10-51"] = {priority = 2, desc = "Wrecker Needed", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-52"] = {priority = 1, desc = "Ambulance Needed", primaryAgency = "POLICE", linked = {"EMS Any"}, peds = "1"},
    ["10-53"] = {priority = 2, desc = "Road Blocked at __", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-54"] = {priority = 2, desc = "Livestock on Highway", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-55"] = {priority = 2, desc = "Intoxicated Driver", primaryAgency = "POLICE", linked = {"EMS44"}, peds = "1"},
    ["10-56"] = {priority = 2, desc = "Intoxicated Pedestrian", primaryAgency = "POLICE", linked = {"EMS44"}, peds = "1"},
    ["10-57"] = {priority = 1, desc = "Hit and Run (F, PI, PD)", primaryAgency = "POLICE", linked = {"10-50"}, peds = "1-2"},
    ["10-58"] = {priority = 2, desc = "Direct Traffic", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-59"] = {priority = 2, desc = "Convoy or Escort", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-60"] = {priority = 2, desc = "Squad in Vicinity", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-61"] = {priority = 3, desc = "Personnel in Area", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-62"] = {priority = 3, desc = "Reply to Message", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-63"] = {priority = 3, desc = "Prepare Make Written Copy", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-64"] = {priority = 3, desc = "Message for Local Delivery", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-65"] = {priority = 3, desc = "Net Message Assignment", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-66"] = {priority = 3, desc = "Message Cancellation", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-67"] = {priority = 3, desc = "Clear for Net Message", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-68"] = {priority = 3, desc = "Dispatch Information", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-69"] = {priority = 3, desc = "Message Received", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-70"] = {priority = 1, desc = "Fire Alarm", primaryAgency = "POLICE", linked = {"F1a"}, peds = "0"},
    ["10-71"] = {priority = 2, desc = "Advise Nature of Fire", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-72"] = {priority = 2, desc = "Report progress on Fire", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-73"] = {priority = 2, desc = "Smoke Report", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-74"] = {priority = 3, desc = "Negative", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-75"] = {priority = 3, desc = "In Contact with __", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-76"] = {priority = 3, desc = "En Route __", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-77"] = {priority = 3, desc = "ETA (Estimated Time of Arrival)", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-78"] = {priority = 1, desc = "Need Assistance", primaryAgency = "POLICE", linked = {"10-33"}, peds = "0"},
    ["10-79"] = {priority = 2, desc = "Notify Coroner", primaryAgency = "POLICE", linked = {"9"}, peds = "1"},
    ["10-80"] = {priority = 1, desc = "Chase in Progress", primaryAgency = "POLICE", linked = {"10-33"}, peds = "1-2"},
    ["10-81"] = {priority = 2, desc = "Breathalyzer Report", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-82"] = {priority = 3, desc = "Reserve Lodging", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-83"] = {priority = 2, desc = "Work School Crossing at _", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-84"] = {priority = 3, desc = "If Meeting __ Advise ETA", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-85"] = {priority = 3, desc = "Delay Due to __", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-86"] = {priority = 3, desc = "Officer / Operator on Duty", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-87"] = {priority = 3, desc = "Pickup / Distribute Checks", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-88"] = {priority = 3, desc = "Present Telephone # of __", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-89"] = {priority = 1, desc = "Bomb Threat", primaryAgency = "POLICE", linked = {"F21"}, peds = "0-5"},
    ["10-90"] = {priority = 1, desc = "Bank Alarm at __", primaryAgency = "POLICE", linked = {}, peds = "1-3"},
    ["10-91"] = {priority = 2, desc = "Pick Up Prisoner / Subject", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-92"] = {priority = 2, desc = "Improperly Parked Vehicle", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-93"] = {priority = 2, desc = "Blockade", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-94"] = {priority = 1, desc = "Drag Racing", primaryAgency = "POLICE", linked = {}, peds = "2-3"},
    ["10-95"] = {priority = 2, desc = "Prisoner / Subject in Custody", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-96"] = {priority = 2, desc = "Mental Subject", primaryAgency = "POLICE", linked = {"EMS43"}, peds = "1"},
    ["10-97"] = {priority = 3, desc = "Check (Test) Signal", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-98"] = {priority = 1, desc = "Prison / Jail Break", primaryAgency = "POLICE", linked = {"10-32"}, peds = "1-3"},
    ["10-99"] = {priority = 1, desc = "Wanted / Stolen Indicated", primaryAgency = "POLICE", linked = {}, peds = "1"},
    ["10-101"] = {priority = 3, desc = "What is Status? Are you secure?", primaryAgency = "POLICE", linked = {}, peds = "0"},
    ["10-106"] = {priority = 3, desc = "Secure (Status is secure)", primaryAgency = "POLICE", linked = {}, peds = "0"}
}

-- Zones (Moved to shared/zones.json, but densities here for reference if needed)
Config.ZoneHotspots = {
    ["LOS_SANTOS_URBAN_CORE"] = 0.3,  -- High density
    ["LOS_SANTOS_SUBURBS"] = 0.2,
    ["SOUTH_LS_INDUSTRIAL_PORT"] = 0.2,
    ["LSIA_AIRPORT"] = 0.15,
    ["BLAINE_COUNTY_RURAL"] = 0.1,  -- Low density
    ["SANDY_SHORES"] = 0.15,
    ["PALETO_BAY_NORTH"] = 0.1,
    ["HIGHWAYS_INTERSTATES"] = 0.25,  -- Medium for accidents
    ["STATE_WATERS_WILDERNESS"] = 0.05  -- Very low
}

-- Role-Specific Configurations
Config.RoleTools = {
    police = {spike = true, pit = true},
    ems = {defib = true, bandage = true},
    fire = {hose = true, ladder = true}
}

Config.FireSpreadRate = 0.1  -- Base rate of fire spread (0.0 to 1.0)

-- AI Settings
Config.AIDensity = {
    solo = 5,  -- AI per call in solo play (playerCount <=1)
    multi = 1  -- AI per call in multiplayer
}

Config.CrowdBaseSize = 3  -- Base crowd PEDs per priority level

-- Simulation Settings
Config.WeatherImpact = true  -- Enable weather mods
Config.EscalationTimer = 300  -- Seconds to escalate unresolved calls
Config.FatigueThreshold = 5  -- Fatigue levels before penalty
Config.CrowdBaseSize = 3  -- PEDs per priority
Config.SkillUnlockThreshold = 10  -- Responses for skill unlock